dbt_qftb:
  outputs:
    dev:
      dbname: postgres
      host: "{{ env_var('DBT_SUPABASE_HOST') }}"
      password: "{{ env_var('DBT_SUPABASE_PASSWORD') }}"
      port: 5432
      schema: public
      threads: 4
      type: postgres
      user: postgres
  target: dev