dbt_qftb:
  outputs:
    dev:
      dbname: postgres
      host: "{{ env_var('DBT_SUPABASE_HOST') }}"
      password: "{{ env_var('DBT_SUPABASE_PASSWORD') }}"
      user: "{{ env_var('DBT_SUPABASE_USER') }}"
      port: 6543
      schema: public
      threads: 4
      type: postgres
  target: dev