name: RAWG Data Pipeline (Fetch & Clean)

on:
  schedule:
    - cron: '0 2 * * 1,3,5'
  workflow_dispatch:

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: uv sync

      - name: Run RAWG Games Pipeline (General)
        env:
          RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          uv run python -m src.etl.fetchers.rawg_fetcher_games
          uv run python -m src.etl.cleaners.rawg_cleaner_games

      - name: Run RAWG Game Details Pipeline (General)
        env:
          RAWG_GAME_DETAILS_API_KEY: ${{ secrets.RAWG_GAME_DETAILS_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          uv run python -m src.etl.fetchers.rawg_fetcher_game_details
          uv run python -m src.etl.cleaners.rawg_cleaner_game_details
      
      - name: Install dbt dev dependencies
        run: uv sync --group dev  

      - name: Run dbt models
        env: 
          DBT_SUPABASE_HOST: ${{ secrets.DBT_SUPABASE_HOST }}
          DBT_SUPABASE_PASSWORD: ${{ secrets.DBT_SUPABASE_PASSWORD }}
          DBT_SUPABASE_USER: ${{ secrets.DBT_SUPABASE_USER }}
        run: |
          uv run dbt deps --project-dir dbt_qftb --profiles-dir .dbt 
          uv run dbt run --project-dir dbt_qftb --profiles-dir .dbt --select marts.* --target ci
          uv run dbt test --project-dir dbt_qftb --profiles-dir .dbt --select marts.* --target ci
